### ISSUE TITLE
wpt-import-stats.py's _compare_commits can say that two commits are both before each other

### ISSUE THREAD

**Issue by foolip** [foolip/ecosystem-infra-stats#4] opened 2018-02-20 04:29 UTC
It uses `git rev-list --count $sha1..$sha2` to determine if one commit is before the other, but there are pairs of commits where both orders will contain commits, namely when the two commits are on two different branches. An example is https://github.com/w3c/web-platform-tests/commit/6eb6ede694a6ba8c070828a601562590d0cdc060 with parents 6b063d67e3 and ed2b76bda7. Both of these are non-zero:
```
git rev-list --count 6b063d67e3..ed2b76bda7
git rev-list --count ed2b76bda7..6b063d67e3
```

I don't think the input to the function is such that this can happen, but if it does the bug will probably be confusing.

We don't really need to order all commits, so maybe this should be renamed to `is_ancestor_of` and use `git merge-base --is-ancestor <commit1> <commit2>
 ` as suggested by https://stackoverflow.com/a/18345268

Alternatively, we could order all commits using `git rev-list --since=2017-07-01T00:00:00Z --topo-order HEAD` ("Show no parents before all of its children are shown") and use that list to determine order. But it'd still be a bit subtle what that order means, it doesn't mean that all later commits are ancestors of all earlier commits, just that the reverse is never true.

@Hexcles WDYT?

**Comment by Hexcles** [comment] 2018-02-28 23:30
Thanks. I forgot `..` would find a path on the version DAG like that...

**Comment by Hexcles** [comment] 2018-03-02 15:41
Actually, changing the comparison function to use `--is-ancestor` doesn't solve the problem.

Neither of the two commits is an ancestor of the other. More fundamentally, we can't derive a total order from a topological order alone. Sorting by time is necessary.

On the other hand, I shall perhaps simplify the whole mapping logic...

**Comment by Hexcles** [comment] 2018-03-03 02:24
I totally confused myself just now during the discussion with @foolip . Now let me try to write down a clarified version of that discussion.

The task is always: given a list of commits (import points or test runs), assign each PR with the earliest commit in the list of which the PR is an ancestor (i.e. the commit "includes" the PR).

## Import stats

My current implementation assumes the list of import points forms a path in the version DAG of WPT, i.e., each import point is the ancestor of the next import point. This property usually holds (since the importer runs in serial and always checks out the head of master), and might only be violated by manual imports in some rare cases. Hence, we have a nice total order to use binary search to find which import point contains a PR. And both `git rev-list foo..bar` and `git merge-base --is-ancestor` equivalently suffice as the comparison function.

(Note: bisecting is needed because the O(|PRs| * |imports|) git invocations otherwise would be too slow.)

## wpt.fyi stats

However, when we want to use this same mechanism to find the earliest wpt.fyi run for a PR, the problem is even worse than this edge case where neither commits are the ancestor of the other. Since the list of commits for which which we have test runs might not be ordered at all, bisecting doesn't work.

We then start to consider solving the problem in the other direction: somehow order the list of commits so that we can find out the last merged PR for *each* commit. (We were thinking `--topo-order` or `--date-order`.)

However, neither is correct. Why? Flattening a non-trivial DAG to a list cannot preserve ancestry information. Here's a simple example:

```
A -> B*  -> D*
 \-> C ->/
```

Both B and D are PR merge points (B could be a rebase-merged PR, while D is a regular two-way merge commit).

Both `--topo-order` and `--date-order` can give the following orderings, and the two orderings are both very likely in the real world:
* D C B A
* D B C A

We can't know whether commit C contains the PR associated with B for sure from a list; in terms of the latency number, it could be skewed towards either direction (seen in the real world).

### Easier solution (cheat)?

Well, I forgot an important new feature that hadn't existed when I wrote import stats -- [WPT master tagger](https://github.com/w3c/web-platform-tests/blob/master/tools/ci/tag_master.py), which tags each PR merge point with a tag like "merge_pr_1234" in order to release pre-generated manifests.

So for any new commit after the tagger was deployed (near the end of last year), we can simply run

```bash
git describe --tags SHA
```

to know the last PR it contains... We didn't have regular wptd runs that far ago, so we can use this trick for wptd latency measuring without problems. @foolip , WDYT?

**Comment by foolip** [comment] 2018-03-04 22:28
Using `git describe` as a way to walk the DAG and find the closest commit is clever, I think we can use it. Can you check if there are merge_pr_* tags for all PRs merged after a certain date, and if they are always on the same commit that the GitHub API claims?

We'll still need the GitHub API to get reliable timestamps, so if the existing tags are no good, we could *create* tags in a temporary repo in order to use `git --describe` with them.

Given a wptd/import commit &rarr; last contained PR mapping, and an ordering of PRs by timestamp, we can reverse it to a PR &rarr; first containing wptd/import commit mapping. Nice!

P.S. If there somehow ends up being tags on both sides of a merge commit, then the tagged commit with the most recent date will be used. Trusting the commit time in edge cases like that fine. There's also `--first-parent`, but that would skip things in case of an reverse merge.

**Comment by Hexcles** [comment] 2018-03-05 00:27
> Given a wptd/import commit → last contained PR mapping, and an ordering of PRs by timestamp, we can reverse it to a PR → first containing wptd/import commit mapping.

We also need the trusted timestamps of imports/wptd runs (for imports, we can trust the commit time in Chromium git; as for wptd runs, we trust the timestamps of test runs), so that when multiple commits have the same last contained PR, we pick the earlier commit to calculate the latency.

The code and the setup of the tagger look good to me. I'll double check the tagged commits against the GitHub API responses.

-------

> P.S. If there somehow ends up being tags on both sides of a merge commit, then the tagged commit with the most recent date will be used. Trusting the commit time in edge cases like that fine. There's also --first-parent, but that would skip things in case of an reverse merge.

Well, `git describe` doesn't really use the timestamps. Its definition of "the most recent", according to [the doc](https://git-scm.com/docs/git-describe#_search_strategy), is:
> If multiple tags were found during the walk then the tag which has the fewest commits different from the input commit-ish will be selected and output. Here fewest commits different is defined as the number of commits which would be shown by git log tag..input will be the smallest number of commits possible.

which is perfect for us! (You can't make (the merge point of) a PR that's merged later the ancestor of (the merge point of) another PR that's merged earlier, unless you `push --force`.)

**Comment by foolip** [comment] 2018-03-09 03:23
That's weird, I'm pretty sure I tested with identical commit graphs where I'd just changed the timestamps of one of the branches and the merge commit. If there's a tie for "the fewest commits", then how is it broken? Maybe it's broken by the sha or something, that could explain what I saw.

**Closed** 2018-04-26 09:47 UTC
